# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluate_left_to_right_cpp <- function(corpus, n_docs, alphabet, n_topics, topic_counts, type_topic_counts, alpha, beta, n_particles, resampling) {
    .Call('_tomer_evaluate_left_to_right_cpp', PACKAGE = 'tomer', corpus, n_docs, alphabet, n_topics, topic_counts, type_topic_counts, alpha, beta, n_particles, resampling)
}

evaluate_npmi_cpp <- function(topics, documents, window_size) {
    .Call('_tomer_evaluate_npmi_cpp', PACKAGE = 'tomer', topics, documents, window_size)
}

evaluate_npmi_with_cache_cpp <- function(topics, documents, window_size, filename) {
    .Call('_tomer_evaluate_npmi_with_cache_cpp', PACKAGE = 'tomer', topics, documents, window_size, filename)
}

compute_markovian_bf_test_cpp <- function(topic_indicators, n_topics, beta) {
    .Call('_tomer_compute_markovian_bf_test_cpp', PACKAGE = 'tomer', topic_indicators, n_topics, beta)
}

compute_chunking_bf_test_cpp <- function(topic_indicators, n_topics, beta) {
    .Call('_tomer_compute_chunking_bf_test_cpp', PACKAGE = 'tomer', topic_indicators, n_topics, beta)
}

compute_chunking_lr_test_cpp <- function(topic_indicators, n_topics, beta) {
    .Call('_tomer_compute_chunking_lr_test_cpp', PACKAGE = 'tomer', topic_indicators, n_topics, beta)
}

evaluate_topic_coherence2_cpp <- function(topics, documents) {
    .Call('_tomer_evaluate_topic_coherence2_cpp', PACKAGE = 'tomer', topics, documents)
}

evaluate_topic_coherence_cpp <- function(topics, documents) {
    .Call('_tomer_evaluate_topic_coherence_cpp', PACKAGE = 'tomer', topics, documents)
}

run_testthat_tests <- function() {
    .Call('_tomer_run_testthat_tests', PACKAGE = 'tomer')
}

