/*
 * Please do not edit this file -- it ensures that your package will export a
 * 'run_testthat_tests()' C routine that can be used to run the Catch unit tests
 * available in your package.
 */
#define CATCH_CONFIG_RUNNER
#include <testthat.h>
#include <Rcpp.h>

// [[Rcpp::export]]
bool run_testthat_tests() {
  bool success = testthat::run_tests();
  return success;
}
